# Old madrid_large_geo_light_sim.launch
operations_json: "use_case/geo_conflict"
geofences_json: "no_geofences"
origin_latitude: 40.65974645776713
origin_longitude: -3.59689676974471
origin_ellipsoidal_height: 0.0  # This altitude is the distance between the ground and the wgs-84 ellipsoid at the origin point
init_time: 0.0  # https://time.is/Unix_time_now
time_horizon: 600
dT: 20
minX: -300
minY: -400
minZ: 0
maxX: 900
maxY: 900
maxZ: 500
deltaX: 10.0
deltaY: 10.0
deltaZ: 10.0
safetyDistance: 10

simulation:
  auto_start:
    - {icao: 3434000, delay: 8.0}
    - {icao: 3434007, delay: 8.0}

  change_param:
    - {icao: 3434007, delay: 20.0, yaml: {name: jamming, type: float, value: 0.6}}
