# Old light_sim.launch
operations_json: "/leon/phase_5/geofence_conflict"
geofences_json: "no_geofences"
origin_latitude: 42.6503418
origin_longitude: -5.7090354
origin_ellipsoidal_height: 56.098  # This altitude is the distance between the ground and the wgs-84 ellipsoid at the origin point
init_time: 0.0  # https://time.is/Unix_time_now
time_horizon: 360
dT: 50
minX: -2000
minY: -4000
minZ: 0
maxX: 1500
maxY: 1000
maxZ: 1000
deltaX: 200.0
deltaY: 200.0
deltaZ: 500.0
safetyDistance: 450

simulation:
  auto_start:
    - {icao: 3434007, delay: 5.0}
    - {icao: 3434009, delay: 288.0}

  # change_param:
  #   - {icao: 5525496, delay: 20.0, yaml: {name: jamming, type: float, value: 0.6}}
