# Old light_sim.launch
operations_json: "arenosillo/geofence_conflict"
geofences_json: "no_geofences"
origin_latitude: 37.10229
origin_longitude: -6.73639
origin_ellipsoidal_height: 51.9697  # This altitude is the distance between the ground and the wgs-84 ellipsoid at the origin point
init_time: 0.0  # https://time.is/Unix_time_now
time_horizon: 800
dT: 10
minX: -5396
minY: -21159
minZ: 0
maxX: 6970
maxY: -12466
maxZ: 694
deltaX: 122
deltaY: 86
deltaZ: 7
safetyDistance: 149
just_one_threat: true

simulation:
  auto_start:
    - {icao: 3434007, delay: 1.0}
    - {icao: 3434009, delay: 1.0}

  # change_param:
  #   - {icao: 3434000, delay: 15.0, yaml: {name: jamming, type: float, value: 0.6}}

  cruising_speed:
    - {icao: 3434007, speed: 0.0}
    - {icao: 3434009, speed: 0.0}