# Old light_sim.launch
operations_json: "arenosillo/loss_separation"
geofences_json: "no_geofences"
origin_latitude: 37.09493
origin_longitude: -6.73646
origin_ellipsoidal_height: 80.0  # This altitude is the distance between the ground and the wgs-84 ellipsoid at the origin point
init_time: 0.0  # https://time.is/Unix_time_now
time_horizon: 360
dT: 50
minX: -5273
minY: -21073
minZ: 0
maxX: 4067
maxY: -8963
maxZ: 687
deltaX: 93
deltaY: 121
deltaZ: 7
safetyDistance: 900
just_one_threat: true

simulation:
  auto_start:
    - {icao: 3434007, delay: 755.0}
    - {icao: 3434009, delay: 5.0}

  # change_param:
  #   - {icao: 5525496, delay: 20.0, yaml: {name: jamming, type: float, value: 0.6}}

  # 4D -> speed should be 0.0 | 3D -> setup a speed
  cruising_speed:
    - {icao: 3434007, speed: 0.0}
    - {icao: 3434009, speed: 0.0}

# ATLANTIC (3434009)
# M600 (3434008)
# SCRABII (3434007)