# Old light_sim.launch
operations_json: "atlas/geofence_conflict"
geofences_json: "no_geofences"
origin_latitude: 38.13891245
origin_longitude: -3.17358946
origin_ellipsoidal_height: 498.0  # This altitude is the distance between the ground and the wgs-84 ellipsoid at the origin point
init_time: 0.0  # https://time.is/Unix_time_now
time_horizon: 800
dT: 10
minX: -10000
minY: -2500
minZ: 0
maxX: 2000
maxY: 2000
maxZ: 1000
deltaX: 200.0
deltaY: 200.0
deltaZ: 500.0
safetyDistance: 450
just_one_threat: true

simulation:
  # auto_start:
  #   - {icao: 3434009, delay: 3.0}
  #   - {icao: 3434000, delay: 3.0}

  # change_param:
  #   - {icao: 3434000, delay: 90.0, yaml: {name: jamming, type: float, value: 0.6}}

  cruising_speed:
    - {icao: 3434009, speed: 0.0}
    - {icao: 3434000, speed: 0.0}