# Old light_sim.launch
operations_json: "atlas/loss_separation"
geofences_json: "no_geofences"
origin_latitude: 38.13891245
origin_longitude: -3.17358946
origin_ellipsoidal_height: 498.0  # This altitude is the distance between the ground and the wgs-84 ellipsoid at the origin point
init_time: 0.0  # https://time.is/Unix_time_now
time_horizon: 360
dT: 20
minX: -10000
minY: -3000
minZ: 0
maxX: 7000
maxY: 2000
maxZ: 1000
deltaX: 100.0
deltaY: 100.0
deltaZ: 500.0
safetyDistance: 550

simulation:
  # auto_start:
  #   - {icao: 3434009, delay: 5.0}
  #   - {icao: 3434000, delay: 16.0}

  # change_param:
  #   - {icao: 5525496, delay: 20.0, yaml: {name: jamming, type: float, value: 0.6}}

  # 4D -> speed should be 0.0 | 3D -> setup a speed
  cruising_speed:
    - {icao: 3434009, speed: 0.0}
    - {icao: 3434000, speed: 0.0}