#!/usr/bin/env python

import sys

from rqt_gauss.gauss_module import GaussPlugin
from rqt_gui.main import Main

plugin = 'rqt_gauss'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
