mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: 95.216.180.100
    port: 1883
    keepalive: 60
serializer: json:dumps
deserializer: json:loads
bridge:
  # adsb
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: test_mqtt.msg:AdsbData
    topic_from: adsb/+
    topic_to: /adsb
  
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: test_mqtt.msg:GeofenceCreation
    topic_from: /geofence_creation
    topic_to: geofence_creation
