mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: 95.216.180.100
    port: 1883
    keepalive: 60
serializer: json:dumps
deserializer: json:loads
bridge:

  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: gauss_msgs_mqtt.msg:UTMGeofenceCreation
    topic_from: /geofence_creation
    topic_to: geofence_creation

  - factory: mqtt_bridge.bridge:AlternativeFlightPlanRosToMqttBridge
    msg_type: gauss_msgs_mqtt.msg:UTMAlternativeFlightPlan
    topic_from: /utmflightplan 
    topic_to: utmflightplan/

