# Old madrid_large_geo_light_sim.launch
operations_json: "madrid/atlantic_geo_conflict"
geofences_json: "madrid/test_geofence"
origin_latitude: 40.65974645776713
origin_longitude: -3.59689676974471
origin_ellipsoidal_height: 675.0  # This altitude is the distance between the ground and the wgs-84 ellipsoid at the origin point
init_time: 0.0  # https://time.is/Unix_time_now
time_horizon: 800
dT: 20
minX: -500
minY: -100
minZ: 0
maxX: 10000
maxY: 2000
maxZ: 700
deltaX: 100.0
deltaY: 100.0
deltaZ: 100.0
safetyDistance: 10

simulation:
  auto_start:
    - {icao: 3434009, delay: 5.0}

  # change_param:
  #   - {icao: 3434009, delay: 23.5, yaml: {name: jamming, type: float, value: 0.6}}
