Header header
uint8 threat_id
int8[] uav_ids
time[] times
uint8[] geofence_ids
Waypoint location

uint8 UAS_IN_CV = 0
uint8 UAS_OUT_OV = 1
uint8 LOSS_OF_SEPARATION = 2
uint8 ALERT_WARNING = 3
uint8 GEOFENCE_INTRUSION = 4
uint8 GEOFENCE_CONFLICT = 5
uint8 TECHNICAL_FAILURE = 6
uint8 COMMUNICATION_FAILURE = 7
uint8 LACK_OF_BATTERY = 8
uint8 JAMMING_ATTACK = 9
uint8 SPOOFING_ATTACK = 10
uint8 GNSS_DEGRADATION = 11

