# Old light_sim.launch
operations_json: "arenosillo_short_loss_separation"
geofences_json: "no_geofences"
origin_latitude: 37.094930
origin_longitude: -6.736467
origin_ellipsoidal_height: 50.278  # This altitude is the distance between the ground and the wgs-84 ellipsoid at the origin point
init_time: 0.0  # https://time.is/Unix_time_now
time_horizon: 360
dT: 50
minX: -5500
minY: -20500
minZ: 0
maxX: 7000
maxY: -7500
maxZ: 1000
deltaX: 500.0
deltaY: 500.0
deltaZ: 500.0
safetyDistance: 800

simulation:
  auto_start:
    - {icao: 3434007, delay: 131.0}
    - {icao: 3434009, delay: 5.0}

  # change_param:
  #   - {icao: 5525496, delay: 20.0, yaml: {name: jamming, type: float, value: 0.6}}
