set(_CATKIN_CURRENT_PACKAGE "ual_communication")
set(ual_communication_VERSION "0.0.0")
set(ual_communication_MAINTAINER "jacevedo <jacevedo@todo.todo>")
set(ual_communication_PACKAGE_FORMAT "2")
set(ual_communication_BUILD_DEPENDS "gauss_msgs" "roscpp" "rospy" "geometry_msgs" "nav_msgs" "std_msgs" "upat_follower")
set(ual_communication_BUILD_EXPORT_DEPENDS "gauss_msgs" "roscpp" "rospy" "geometry_msgs" "nav_msgs" "std_msgs" "upat_follower")
set(ual_communication_BUILDTOOL_DEPENDS "catkin")
set(ual_communication_BUILDTOOL_EXPORT_DEPENDS )
set(ual_communication_EXEC_DEPENDS "gauss_msgs" "roscpp" "rospy" "geometry_msgs" "nav_msgs" "std_msgs" "upat_follower")
set(ual_communication_RUN_DEPENDS "gauss_msgs" "roscpp" "rospy" "geometry_msgs" "nav_msgs" "std_msgs" "upat_follower")
set(ual_communication_TEST_DEPENDS )
set(ual_communication_DOC_DEPENDS )
set(ual_communication_URL_WEBSITE "")
set(ual_communication_URL_BUGTRACKER "")
set(ual_communication_URL_REPOSITORY "")
set(ual_communication_DEPRECATED "")